server {
    listen 80;
    server_name nightbox.in www.nightbox.in;

    root /var/www/nightbox/nightbox-p4/web;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
